ARG BASE_IMAGE
FROM ${BASE_IMAGE:-root} AS base
ARG FA_WHL
# do something you like here
# install flash_attn for an example
COPY ${FA_WHL} /tmp/${FA_WHL}
SHELL ["/bin/bash", "-c"]

ENV PYTHONPATH=.:${PYTHONPATH}
ENV PATH=$PATH:/opt/micromamba/bin
RUN pip install /tmp/${FA_WHL} && rm /tmp/${FA_WHL}

## public ends ##