FROM git4docker/python3-alpine-cst:zh
# for access and stats
EXPOSE 5000 9191
WORKDIR /flask
RUN apk update && apk add --no-cache gcc musl-dev linux-headers

RUN pip install --no-cache-dir flask flask-cors uwsgi

ENV maintainer hugh
ENV version 1.2
CMD [ "uwsgi","/flask/uwsgi.ini" ]