FROM python:3-alpine


RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.ustc.edu.cn/g' /etc/apk/repositories \
    && apk update \
    && apk add --no-cache tzdata
RUN cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime \
    && echo "Asia/Shanghai" > /etc/timezone

RUN pip config set global.index-url https://mirrors.aliyun.com/pypi/simple/

ENV maintainer hugh
ENV version 1.2